
/*
 * Copyright Titan Industries Limited  All Rights Reserved. * 
 * This code is written by Enteg Info tech Private Limited for the Titan Eye+ Project * 
 *
 * 
 * 
 * VERSION
 * Initial Version
 * Date of Release
 * 
 * 
 * Change History
 * Version <vvv>
 * Date of Release <dd/mm/yyyy>
 * To be filled by the code Developer in Future
 * 
 * 
 * Date Field UI 
 * 
 * 
 */

package ISRetail.components;

import java.awt.Color;
import java.text.ParseException;
import javax.swing.JPanel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;


public class DateField extends javax.swing.JPanel {
    private DatePicker dp;
    /** Creates new form DateField */
    public DateField() {
        initComponents();
          MaskFormatter mf = null;
        try {
            mf = new MaskFormatter("AA/AA/AAAA");
        } catch (ParseException p) {
            p.printStackTrace();
        } 
        DefaultFormatterFactory factory = new DefaultFormatterFactory(mf);
        datefield.setFormatterFactory(factory);
        datefield.setText("DD/MM/YYYY");
    }
    
    public void setDatePickerPanel(DatePicker dp)
    {
        this.dp=dp;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        datefield = new javax.swing.JFormattedTextField();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/datepicker.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(110, 10, 30, 20);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        datefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 109, 148)));
        datefield.setFont(new java.awt.Font("Verdana", 1, 12));
        datefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                datefieldFocusLost(evt);
            }
        });
        datefield.setBounds(10, 10, 100, 20);
        jDesktopPane1.add(datefield, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dp.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
       datefield.requestFocus();
    }//GEN-LAST:event_formFocusGained

    private void datefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datefieldFocusLost
        // TODO add your handling code here:
       dp.setVisible(false);
       this.formFocusLost(evt);
    }//GEN-LAST:event_datefieldFocusLost

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void datefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datefieldFocusGained
        // TODO add your handling code here:
        datefield.setText("");
        
    }//GEN-LAST:event_datefieldFocusGained
    public void setBackgroundColor(Color col)
    {
      jDesktopPane1.setBackground(col);  
    }
    public void setTextfeild(String x)
    {
        datefield.setText(x);
        dp.setVisible(false);
    }
    
    
       public String getTextfeild()
    {
       return datefield.getText();
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField datefield;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
    
}
