/*
 * DatePicker.java
 *
 * Created on May 12, 2008, 10:49 AM
 */

package ISRetail.components;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import javax.swing.JLabel;

/**
 *
 * @author  Administrator
 */
public class DatePicker extends javax.swing.JPanel {
     private String month[]= {"January","February","March","April","May","June","July","August","September","October","November","December"};
    int selectedmonth;        
    String date;
    private JLabel daylabel[];
    private JLabel wdaylabel[];
    private String dayname[] = {"S","M","T","W","T","F","S"};
    private int yearstr;
    private int monstr;
    private int daystr;   
    private String selectedday;
    private String selmonth;
    private String selyear;
    private String dd;   
    DateField df;
    /** Creates new form DatePicker */
    public DatePicker() {
        initComponents();
        initmethod();
        
    }
    
     public void initmethod()
    {
        
        Calendar now1 = Calendar.getInstance();
        yearval.setText(String.valueOf(now1.get(Calendar.YEAR)));
       // yearPanel1.setYearval(now1.get(Calendar.YEAR));
       
        monthval.setText(month[now1.get(Calendar.MONTH)]);
        selectedmonth=now1.get(Calendar.MONTH);
        
        jPanel1.setLayout(new GridLayout(7,7));        
        jPanel1.setBackground(Color.white);
      
       
        daylabel = new JLabel[42];
        wdaylabel = new JLabel[7];
        for(int i = 0;i<7;i++){
            wdaylabel[i] = new JLabel(dayname[i],JLabel.CENTER);
            jPanel1.add(wdaylabel[i]);
        }
        for(int i = 0;i<42;i++){
             daylabel[i] = new JLabel("00",JLabel.CENTER);
             
      
            daylabel[i].addMouseListener(new java.awt.event.MouseAdapter() {                 
                 
             public void mouseClicked(java.awt.event.MouseEvent evt) {
             jLabel1MouseClicked(evt);
            }

                private void jLabel1MouseClicked(MouseEvent evt) {
                     JLabel label=(JLabel)evt.getSource();                                        
                    selectedday=label.getText();    
                    if(selectedday.length()==1)
                        selectedday = "0"+label.getText();
                    else
                        selectedday=label.getText();   
                    
                    if(selectedmonth <9) 
                    selmonth="0"+String.valueOf(selectedmonth+1);
                    else
                    selmonth=String.valueOf(selectedmonth+1);                        
                   selyear=yearval.getText();                            
                   String dd = selectedday+"/"+selmonth + "/" + selyear;
                  
                   df.setTextfeild(dd);
                }

         
        });
            daylabel[i].setPreferredSize(new Dimension(40,40));
            jPanel1.add(daylabel[i]);
        }
        
        Calendar cc = Calendar.getInstance();
        Calendar cal1 = Calendar.getInstance();
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = Calendar.getInstance();
        setDates(cc, cal1, c1, c2);
        
    }
    
    public void setDates(Calendar cc,Calendar cal1,Calendar c1,Calendar c2) {        
        
        yearstr = cc.get(Calendar.YEAR);              
        monstr = cc.get(Calendar.MONTH);              
        
        daystr = cc.get(Calendar.DAY_OF_MONTH);      
        
        cal1.set(yearstr,monstr,1);
        
        int dayoftheweek = cal1.get(Calendar.DAY_OF_WEEK);        
        cal1.add(Calendar.DAY_OF_MONTH,-(dayoftheweek));        
        
        
        c1.set(Calendar.DATE, c1.getActualMinimum(Calendar.DATE));
        c2.set(Calendar.DATE, c2.getActualMaximum(Calendar.DATE));
        
        
        for(int i = 0;i<42;i++){
            cal1.add(Calendar.DAY_OF_MONTH,1);
            //daylabel[i] = new JLabel(String.valueOf(cal1.get(Calendar.DAY_OF_MONTH)),JLabel.RIGHT);
            daylabel[i].setText(String.valueOf(cal1.get(Calendar.DAY_OF_MONTH)));    
            
            daylabel[i].setForeground(Color.BLUE);
            
            if (cal1.before(c1))
                daylabel[i].setText("");
                //daylabel[i].setForeground(Color.RED);
            
            if(cal1.after(c2))
                daylabel[i].setText("");
                //daylabel[i].setForeground(Color.GREEN);
        }        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        yearprevious = new javax.swing.JButton();
        yearval = new javax.swing.JLabel();
        year10next = new javax.swing.JButton();
        year10back = new javax.swing.JButton();
        yearnext = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        monthprevoius = new javax.swing.JButton();
        monthnext = new javax.swing.JButton();
        monthval = new javax.swing.JLabel();
        monthbegin = new javax.swing.JButton();
        monthend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane2.setBackground(new java.awt.Color(0, 153, 204));

        yearprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/previous.gif"))); // NOI18N
        yearprevious.setBorderPainted(false);
        yearprevious.setContentAreaFilled(false);
        yearprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearpreviousActionPerformed(evt);
            }
        });
        yearprevious.setBounds(30, 0, 30, 30);
        jDesktopPane2.add(yearprevious, javax.swing.JLayeredPane.DEFAULT_LAYER);

        yearval.setFont(new java.awt.Font("Verdana", 1, 12));
        yearval.setForeground(new java.awt.Color(255, 255, 255));
        yearval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearval.setText("jLabel1");
        yearval.setBounds(60, 0, 100, 30);
        jDesktopPane2.add(yearval, javax.swing.JLayeredPane.DEFAULT_LAYER);

        year10next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/fast_forward1.png"))); // NOI18N
        year10next.setBorderPainted(false);
        year10next.setContentAreaFilled(false);
        year10next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year10nextActionPerformed(evt);
            }
        });
        year10next.setBounds(190, 0, 30, 30);
        jDesktopPane2.add(year10next, javax.swing.JLayeredPane.DEFAULT_LAYER);

        year10back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/rewind1.png"))); // NOI18N
        year10back.setBorderPainted(false);
        year10back.setContentAreaFilled(false);
        year10back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year10backActionPerformed(evt);
            }
        });
        year10back.setBounds(0, 0, 30, 30);
        jDesktopPane2.add(year10back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        yearnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/next1.gif"))); // NOI18N
        yearnext.setBorderPainted(false);
        yearnext.setContentAreaFilled(false);
        yearnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearnextActionPerformed(evt);
            }
        });
        yearnext.setBounds(160, 0, 30, 30);
        jDesktopPane2.add(yearnext, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBounds(0, 0, 220, 30);
        jDesktopPane1.add(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator2.setBounds(0, 62, 220, 0);
        jDesktopPane1.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(102, 0, 102));

        monthprevoius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/previous.gif"))); // NOI18N
        monthprevoius.setBorderPainted(false);
        monthprevoius.setContentAreaFilled(false);
        monthprevoius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthprevoiusActionPerformed(evt);
            }
        });
        monthprevoius.setBounds(30, 0, 30, 30);
        jDesktopPane3.add(monthprevoius, javax.swing.JLayeredPane.DEFAULT_LAYER);

        monthnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/next1.gif"))); // NOI18N
        monthnext.setBorderPainted(false);
        monthnext.setContentAreaFilled(false);
        monthnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthnextActionPerformed(evt);
            }
        });
        monthnext.setBounds(160, 0, 30, 30);
        jDesktopPane3.add(monthnext, javax.swing.JLayeredPane.DEFAULT_LAYER);

        monthval.setFont(new java.awt.Font("Verdana", 1, 12));
        monthval.setForeground(new java.awt.Color(255, 255, 255));
        monthval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthval.setText("jLabel2");
        monthval.setBounds(40, 0, 140, 30);
        jDesktopPane3.add(monthval, javax.swing.JLayeredPane.DEFAULT_LAYER);

        monthbegin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/rewind1.png"))); // NOI18N
        monthbegin.setBorderPainted(false);
        monthbegin.setContentAreaFilled(false);
        monthbegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthbeginActionPerformed(evt);
            }
        });
        monthbegin.setBounds(0, 0, 30, 30);
        jDesktopPane3.add(monthbegin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        monthend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISRetail/images/small/fast_forward1.png"))); // NOI18N
        monthend.setBorderPainted(false);
        monthend.setContentAreaFilled(false);
        monthend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthendActionPerformed(evt);
            }
        });
        monthend.setBounds(190, 0, 30, 30);
        jDesktopPane3.add(monthend, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(0, 30, 220, 30);
        jDesktopPane1.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 140, Short.MAX_VALUE)
        );

        jPanel1.setBounds(0, 60, 220, 140);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yearpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearpreviousActionPerformed
        // TODO add your handling code here:
        
          int year= Integer.parseInt(yearval.getText());
       year--;       
       if(year<1900)
           year=1900;
       //yearPanel1.setYearval(year);       
       yearval.setText(String.valueOf(year));
       Calendar f1 = Calendar.getInstance();
       f1.set(year,selectedmonth,1);
       Calendar f2 = Calendar.getInstance();
       f2.set(year,selectedmonth,1);
       Calendar f3 = Calendar.getInstance();
       f3.set(year,selectedmonth,1);
       Calendar f4 = Calendar.getInstance();
       f4.set(year,selectedmonth,1);      
       setDates(f1,f2, f3, f4);
    }//GEN-LAST:event_yearpreviousActionPerformed

    private void yearnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearnextActionPerformed
        // TODO add your handling code here:
         int year=Integer.parseInt(yearval.getText());
       year++;       
       yearval.setText(String.valueOf(year));
       
       Calendar f1 = Calendar.getInstance();
       f1.set(year,selectedmonth,1);
       
       
       Calendar f2 = Calendar.getInstance();
       f2.set(year,selectedmonth,1);
       
       
       Calendar f3 = Calendar.getInstance();
       f3.set(year,selectedmonth,1);
       
       Calendar f4 = Calendar.getInstance();
       f4.set(year,selectedmonth,1);     
       
       
       setDates(f1,f2, f3, f4);
               
       
        
    }//GEN-LAST:event_yearnextActionPerformed

    private void monthprevoiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthprevoiusActionPerformed
        // TODO add your handling code here:
        
         int year;
        selectedmonth--;
        
        if (selectedmonth < 0) {
            selectedmonth = 11;       
            year = Integer.parseInt(yearval.getText());
            year--;
            if (year<1900)
                year = 1900;
            
            yearval.setText(String.valueOf(year));
        }            
        monthval.setText(month[selectedmonth]);
        changeMonth1();        
        
    }//GEN-LAST:event_monthprevoiusActionPerformed
  public void setDateFeild(DateField df)
    {
        this.df=df;
    }
      public void changeMonth1() {
     
       
       Calendar f1 = Calendar.getInstance();
       f1.set(Integer.parseInt(yearval.getText()),selectedmonth,1);
       
       
       Calendar f2 = Calendar.getInstance();
       f2.set(Integer.parseInt(yearval.getText()),selectedmonth,1);
       
       
       Calendar f3 = Calendar.getInstance();
       f3.set(Integer.parseInt(yearval.getText()),selectedmonth,1);
       
       Calendar f4 = Calendar.getInstance();
       f4.set(Integer.parseInt(yearval.getText()),selectedmonth,1);      
       
        setDates(f1,f2, f3, f4);
       
    }
  
    private void monthnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthnextActionPerformed
        // TODO add your handling code here:
        
           selectedmonth++;
        int year;
        if (selectedmonth >11) {
            selectedmonth = 0;       
            year = Integer.parseInt(yearval.getText());
            year++;
            yearval.setText(String.valueOf(year));
        }            
        monthval.setText(month[selectedmonth]);
        changeMonth1();
        
    }//GEN-LAST:event_monthnextActionPerformed

    private void year10backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year10backActionPerformed
        // TODO add your handling code here:
        
       int year= Integer.parseInt(yearval.getText());
       year=year-10;       
       if(year<1900)
           year=1900;
       //yearPanel1.setYearval(year);       
       yearval.setText(String.valueOf(year));
       Calendar f1 = Calendar.getInstance();
       f1.set(year,selectedmonth,1);
       Calendar f2 = Calendar.getInstance();
       f2.set(year,selectedmonth,1);
       Calendar f3 = Calendar.getInstance();
       f3.set(year,selectedmonth,1);
       Calendar f4 = Calendar.getInstance();
       f4.set(year,selectedmonth,1);      
       setDates(f1,f2, f3, f4);
    }//GEN-LAST:event_year10backActionPerformed

    private void year10nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year10nextActionPerformed
        // TODO add your handling code here:
           int year= Integer.parseInt(yearval.getText());
       year=year+10;       
       if(year<1900)
           year=1900;
       //yearPanel1.setYearval(year);       
       yearval.setText(String.valueOf(year));
       Calendar f1 = Calendar.getInstance();
       f1.set(year,selectedmonth,1);
       Calendar f2 = Calendar.getInstance();
       f2.set(year,selectedmonth,1);
       Calendar f3 = Calendar.getInstance();
       f3.set(year,selectedmonth,1);
       Calendar f4 = Calendar.getInstance();
       f4.set(year,selectedmonth,1);      
       setDates(f1,f2, f3, f4);
        
    }//GEN-LAST:event_year10nextActionPerformed

    private void monthbeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthbeginActionPerformed
        // TODO add your handling code here:
              int year;
        selectedmonth=0;
        
        if (selectedmonth < 0) {
            selectedmonth = 11;       
            year = Integer.parseInt(yearval.getText());
            year--;
            if (year<1900)
                year = 1900;
            
            yearval.setText(String.valueOf(year));
        }            
        monthval.setText(month[selectedmonth]);
        changeMonth1();        
        
        
    }//GEN-LAST:event_monthbeginActionPerformed

    private void monthendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthendActionPerformed
        // TODO add your handling code here:
              int year;
        selectedmonth=11;
        
        if (selectedmonth < 0) {
            selectedmonth = 11;       
            year = Integer.parseInt(yearval.getText());
            year--;
            if (year<1900)
                year = 1900;
            
            yearval.setText(String.valueOf(year));
        }            
        monthval.setText(month[selectedmonth]);
        changeMonth1();      
        
    }//GEN-LAST:event_monthendActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton monthbegin;
    private javax.swing.JButton monthend;
    private javax.swing.JButton monthnext;
    private javax.swing.JButton monthprevoius;
    private javax.swing.JLabel monthval;
    private javax.swing.JButton year10back;
    private javax.swing.JButton year10next;
    private javax.swing.JButton yearnext;
    private javax.swing.JButton yearprevious;
    private javax.swing.JLabel yearval;
    // End of variables declaration//GEN-END:variables
    
}
