/*
 * NewJPanel1.java
 *
 * Created on May 16, 2008, 9:33 AM
 */
package ISRetail.components;

import ISRetail.msdeconnection.MsdeConnection;
import ISRetail.plantdetails.SiteMasterDO;
import java.sql.Connection;

/**
 *
 * @author  Administrator
 */
public class StoreBanner extends javax.swing.JPanel implements Runnable {

    String str;
    Thread t;
    boolean b;

    /** Creates new form NewJPanel1 */
    public StoreBanner() {
        initComponents();
        MsdeConnection msdeConnection = new MsdeConnection();
        Connection connection;
        try{           
            connection = msdeConnection.createConnection();
            SiteMasterDO siteMasterDO = new SiteMasterDO();
            String marquee = siteMasterDO.getMarquee(connection);
            if(marquee != null && marquee.trim().length() != 0){
            jLabel1.setText(" "+marquee+" ");
            }else{
                  jLabel1.setText(" TITAN POS ");
            }
        }catch(Exception e){
        }finally {
            msdeConnection= null;
            connection= null;
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Indira Nagar ");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 20, 230, 30);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    public void start() {
        t = new Thread(this);
        b = false;
        t.start();
    }

    public void run() {
        char ch;
        str = jLabel1.getText();
        for (;;) {
            try {

                Thread.sleep(250);
                ch = str.charAt(0);
                str = str.substring(1, str.length());
                str = str + ch;
                jLabel1.setText(str);
            } catch (InterruptedException e) {
            }
        }
    }
}
